import { GoogleGenAI } from '@google/genai';
import { VOICE_PERSONAS, VoicePersonaId } from '@/types';

const apiKey = process.env.GEMINI_API_KEY || '';

export const isGeminiConfigured = () => {
  return !!apiKey && !apiKey.includes('placeholder') && apiKey.trim().length > 10;
};

export const getGeminiClient = () => {
  if (!isGeminiConfigured()) return null;
  return new GoogleGenAI({ apiKey });
};

/**
 * Generate music audio with Lyria 3.5
 */
export async function generateLyriaMusic(
  prompt: string,
  genres: string[] = []
): Promise<{ audioBuffer: Buffer; lyrics: string; contentType: string }> {
  const client = getGeminiClient();

  const fullPrompt = [
    `High-energy electronic dance track.`,
    genres.length > 0 ? `Genres & Style: ${genres.join(', ')}.` : '',
    `User Prompt: ${prompt}`,
    `Create a dynamic club mix with a punchy intro, driving bassline, and massive drop suitable for a live DJ set.`,
  ]
    .filter(Boolean)
    .join(' ');

  if (client) {
    try {
      console.log('Invoking Lyria 3.5 for prompt:', fullPrompt);
      const interaction = await client.interactions.create({
        model: 'lyria-3.5',
        input: fullPrompt,
        response_format: { type: 'audio' },
      });

      if (interaction.output_audio && interaction.output_audio.data) {
        const audioBuffer = Buffer.from(interaction.output_audio.data, 'base64');
        const lyrics = interaction.output_text || 'Generated by Google DeepMind Lyria 3.5';
        return {
          audioBuffer,
          lyrics,
          contentType: interaction.output_audio.mime_type || 'audio/mpeg',
        };
      }
    } catch (err: unknown) {
      console.warn('Lyria 3.5 generation failed, attempting preview model:', err);
      try {
        const clipInteraction = await client.interactions.create({
          model: 'lyria-3-clip-preview',
          input: fullPrompt,
        });
        if (clipInteraction.output_audio && clipInteraction.output_audio.data) {
          const audioBuffer = Buffer.from(clipInteraction.output_audio.data, 'base64');
          return {
            audioBuffer,
            lyrics: clipInteraction.output_text || 'Lyria 3 Clip Preview',
            contentType: 'audio/mpeg',
          };
        }
      } catch (clipErr) {
        console.error('Lyria fallback failed:', clipErr);
      }
    }
  }

  // Fallback demo synth beat generator for testing when no Gemini key is provided
  console.log('Using simulated electronic track for development demo');
  const buffer = generateDemoClubBeatWav(130, 20); // 20 seconds 130 BPM energetic techno synth
  return {
    audioBuffer: buffer,
    lyrics: `[Generated in Demo Rave Mode]\nBeat: 130 BPM Cyber Bassline\nPrompt: ${prompt}`,
    contentType: 'audio/wav',
  };
}

/**
 * Synthesize DJ MC Greeting voiceover with Gemini 3.8 Flash-Lite TTS
 */
export async function generateGreetingTTS(
  greetingText: string,
  personaId: VoicePersonaId = 'hype_mc'
): Promise<{ audioBuffer: Buffer; contentType: string }> {
  const client = getGeminiClient();
  const persona = VOICE_PERSONAS[personaId] || VOICE_PERSONAS.hype_mc;

  if (client) {
    try {
      console.log(`Invoking gemini-3.8-flash-lite-tts with voice ${persona.geminiVoice}`);
      const interaction = await client.interactions.create({
        model: 'gemini-3.8-flash-lite-tts',
        input: [
          {
            type: 'user_input',
            content: [
              {
                type: 'text',
                text: greetingText,
                annotations: [
                  {
                    type: 'speech_metadata',
                    style: persona.styleHint,
                  },
                ],
              },
            ],
          },
        ],
        response_format: { type: 'audio' },
        generation_config: {
          speech_config: [{ voice: persona.geminiVoice }],
        },
      });

      if (interaction.output_audio && interaction.output_audio.data) {
        return {
          audioBuffer: Buffer.from(interaction.output_audio.data, 'base64'),
          contentType: interaction.output_audio.mime_type || 'audio/wav',
        };
      }
    } catch (err) {
      console.error('Gemini TTS generation error:', err);
    }
  }

  // Fallback synthesized speech tone / chime for demo
  const fallbackBuffer = generateDemoVoiceToneWav(greetingText);
  return {
    audioBuffer: fallbackBuffer,
    contentType: 'audio/wav',
  };
}

/**
 * Enhance music prompt using Gemini 3.8 Flash
 */
export async function enhancePrompt(
  rawPrompt: string,
  selectedGenres: string[]
): Promise<string> {
  const client = getGeminiClient();
  if (!client) {
    const genresStr = selectedGenres.length ? selectedGenres.join(' and ') : 'electronic';
    return `High energy ${genresStr} anthem featuring punchy drums, pulsating bass, and euphoric festival drops: ${rawPrompt}`;
  }

  try {
    const interaction = await client.interactions.create({
      model: 'gemini-3.8-flash',
      input: `You are an expert electronic music producer and festival DJ prompt engineer for Google DeepMind Lyria 3.5.
Given this user music idea: "${rawPrompt}"
And selected vibes: "${selectedGenres.join(', ')}"

Rewrite this into a single, punchy, vivid 1-2 sentence music generation prompt that specifies rhythm, BPM (e.g. 124-132 BPM), key instruments, mood, and dance energy.
Do NOT include preamble, markdown or quotes, only output the enhanced prompt text:`,
    });

    return interaction.output_text?.trim() || rawPrompt;
  } catch (err) {
    console.error('Prompt enhancement error:', err);
    return rawPrompt;
  }
}

/**
 * Generates a clean 16-bit PCM WAV audio buffer in Node for demo beats
 */
function generateDemoClubBeatWav(bpm: number = 128, durationSec: number = 15): Buffer {
  const sampleRate = 24000;
  const numSamples = sampleRate * durationSec;
  const pcm = new Int16Array(numSamples);

  const beatPeriod = (60 / bpm) * sampleRate;

  for (let i = 0; i < numSamples; i++) {
    const t = i / sampleRate;
    const beatPos = i % beatPeriod;
    const beatPhase = beatPos / sampleRate;

    // Kick drum: pitch sweep from 150Hz to 40Hz with exponential decay
    let kick = 0;
    if (beatPhase < 0.25) {
      const kickFreq = 40 + 110 * Math.exp(-beatPhase * 25);
      kick = Math.sin(2 * Math.PI * kickFreq * beatPhase) * Math.exp(-beatPhase * 12);
    }

    // Hi-hat on the off-beat
    let hihat = 0;
    const offbeatPos = (i + beatPeriod / 2) % beatPeriod;
    const offbeatPhase = offbeatPos / sampleRate;
    if (offbeatPhase < 0.08) {
      hihat = (Math.random() * 2 - 1) * Math.exp(-offbeatPhase * 40) * 0.4;
    }

    // Synth bassline (sawtooth filtered arpeggio)
    const noteStep = Math.floor(t * 8) % 8;
    const notes = [55, 55, 65.4, 73.4, 55, 82.4, 73.4, 65.4]; // A1 arpeggio
    const freq = notes[noteStep];
    const synth = ((t * freq) % 1 > 0.5 ? 0.3 : -0.3) * Math.exp(-(beatPhase % 0.125) * 8);

    const mix = (kick * 0.65 + hihat * 0.25 + synth * 0.4) * 0.8;
    pcm[i] = Math.max(-32767, Math.min(32767, Math.floor(mix * 32767)));
  }

  return encodeWav(pcm, sampleRate);
}

/**
 * Generates a pleasant voice-like FM bell/shoutout chime for demo mode
 */
function generateDemoVoiceToneWav(text: string): Buffer {
  const sampleRate = 24000;
  const durationSec = Math.min(6, Math.max(2, text.split(' ').length * 0.4));
  const numSamples = Math.floor(sampleRate * durationSec);
  const pcm = new Int16Array(numSamples);

  for (let i = 0; i < numSamples; i++) {
    const t = i / sampleRate;
    // DJ intro chime (two-tone chime + rising chord)
    const f1 = t < 0.6 ? 440 : 554.37;
    const f2 = t < 0.6 ? 659.25 : 880;
    const env = Math.exp(-((t % 0.6) * 4));
    const tone = (Math.sin(2 * Math.PI * f1 * t) + Math.sin(2 * Math.PI * f2 * t)) * 0.5 * env;
    pcm[i] = Math.max(-32767, Math.min(32767, Math.floor(tone * 18000)));
  }

  return encodeWav(pcm, sampleRate);
}

function encodeWav(samples: Int16Array, sampleRate: number): Buffer {
  const byteLength = samples.length * 2;
  const buffer = Buffer.alloc(44 + byteLength);

  buffer.write('RIFF', 0);
  buffer.writeUInt32LE(36 + byteLength, 4);
  buffer.write('WAVE', 8);
  buffer.write('fmt ', 12);
  buffer.writeUInt32LE(16, 16);
  buffer.writeUInt16LE(1, 20); // PCM
  buffer.writeUInt16LE(1, 22); // Mono
  buffer.writeUInt32LE(sampleRate, 24);
  buffer.writeUInt32LE(sampleRate * 2, 28); // Byte rate
  buffer.writeUInt16LE(2, 32); // Block align
  buffer.writeUInt16LE(16, 34); // Bits per sample
  buffer.write('data', 36);
  buffer.writeUInt32LE(byteLength, 40);

  for (let i = 0; i < samples.length; i++) {
    buffer.writeInt16LE(samples[i], 44 + i * 2);
  }

  return buffer;
}
